name: Gas Snapshot 
on: 
  push:
      # branches:
      #   - master

jobs: 
  Run-Snapshot:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
     
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - run: | 
        forge snapshot
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "snapshot"
        git push